name: Newsfile

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

permissions: {}

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: # Needed for comparison
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      - run: pip install 'towncrier>=23.6.0'
      - name: ":newspaper: Newsfile"
        run: ./scripts/check-newsfragment
